/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as EditorRouteRouteImport } from "./routes/editor/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PreviewCvIdRouteImport } from "./routes/preview/$cvId"
import { Route as EditorNewRouteImport } from "./routes/editor/new"
import { Route as EditorCvIdRouteImport } from "./routes/editor/$cvId"

const EditorRouteRoute = EditorRouteRouteImport.update({
  id: "/editor",
  path: "/editor",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewCvIdRoute = PreviewCvIdRouteImport.update({
  id: "/preview/$cvId",
  path: "/preview/$cvId",
  getParentRoute: () => rootRouteImport,
} as any)
const EditorNewRoute = EditorNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => EditorRouteRoute,
} as any)
const EditorCvIdRoute = EditorCvIdRouteImport.update({
  id: "/$cvId",
  path: "/$cvId",
  getParentRoute: () => EditorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/editor": typeof EditorRouteRouteWithChildren
  "/editor/$cvId": typeof EditorCvIdRoute
  "/editor/new": typeof EditorNewRoute
  "/preview/$cvId": typeof PreviewCvIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/editor": typeof EditorRouteRouteWithChildren
  "/editor/$cvId": typeof EditorCvIdRoute
  "/editor/new": typeof EditorNewRoute
  "/preview/$cvId": typeof PreviewCvIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/editor": typeof EditorRouteRouteWithChildren
  "/editor/$cvId": typeof EditorCvIdRoute
  "/editor/new": typeof EditorNewRoute
  "/preview/$cvId": typeof PreviewCvIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/editor"
    | "/editor/$cvId"
    | "/editor/new"
    | "/preview/$cvId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/editor" | "/editor/$cvId" | "/editor/new" | "/preview/$cvId"
  id:
    | "__root__"
    | "/"
    | "/editor"
    | "/editor/$cvId"
    | "/editor/new"
    | "/preview/$cvId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRouteRoute: typeof EditorRouteRouteWithChildren
  PreviewCvIdRoute: typeof PreviewCvIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/editor": {
      id: "/editor"
      path: "/editor"
      fullPath: "/editor"
      preLoaderRoute: typeof EditorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/preview/$cvId": {
      id: "/preview/$cvId"
      path: "/preview/$cvId"
      fullPath: "/preview/$cvId"
      preLoaderRoute: typeof PreviewCvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/editor/new": {
      id: "/editor/new"
      path: "/new"
      fullPath: "/editor/new"
      preLoaderRoute: typeof EditorNewRouteImport
      parentRoute: typeof EditorRouteRoute
    }
    "/editor/$cvId": {
      id: "/editor/$cvId"
      path: "/$cvId"
      fullPath: "/editor/$cvId"
      preLoaderRoute: typeof EditorCvIdRouteImport
      parentRoute: typeof EditorRouteRoute
    }
  }
}

interface EditorRouteRouteChildren {
  EditorCvIdRoute: typeof EditorCvIdRoute
  EditorNewRoute: typeof EditorNewRoute
}

const EditorRouteRouteChildren: EditorRouteRouteChildren = {
  EditorCvIdRoute: EditorCvIdRoute,
  EditorNewRoute: EditorNewRoute,
}

const EditorRouteRouteWithChildren = EditorRouteRoute._addFileChildren(
  EditorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRouteRoute: EditorRouteRouteWithChildren,
  PreviewCvIdRoute: PreviewCvIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
